from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('faculty', views.faculty, name='faculty'),
    path('faculty/<int:pk>',views.FacultyDetailPage.as_view(),name ='facultyinfo'),
    path('events',views.EventsListView.as_view(),name='events'),
    path('about', views.aboutus, name='about'),
    path('academics', views.academics, name='academics'),
    path('academics-cse', views.academicscse, name='academics-cse'),
    path('academics-ece', views.academicsece, name='academics-ece'),
    path('academics-dsai', views.academicsdsai, name='academics-dsai'),
    path('contact', views.contact, name='contact'),
    path('gallery', views.GalleryCategories.as_view(), name='gallery'),
    path('gallery/<cat_id>', views.gallery, name='galleryDetail'),
    path('jobs',views.JobsListView.as_view(),name='jobs'),
    path('newstack', views.newstack, name='newstack'),
    path('placements', views.placements, name='placements'),
    path('research', views.research, name='research'),
    path('administration', views.administration, name='administration'),
    path('board-of-governers', views.bog, name='bog'),
    path('finance-committee', views.financeCommittee, name='ficommit'),
    path('senate', views.senate, name='senate'),
    path('staff', views.staff, name='staff'),
    path('admissions', views.admissions, name='admissions'),
    path('ug', views.ugcse, name='ug'),
    path('phd', views.phd, name='phd'),
    path('faq', views.faqs, name='faq'),
    path('scholarships', views.Scholarships, name='scholarships'),
    path('chatbot', views.chatbot, name='chatbot'),
    path('campus', views.campus, name='campus'),
    path('magazine',views.magazine,name='magazine'),
    path('magazine',views.clubs,name='clubs'),
    path('fees',views.fees,name='fees'),
    path('admission_procedure',views.admissionProcedure,name='admission_procedure'),
    path('announcements',views.AnnouncementsListView.as_view(),name='announcements'),
    path('updates',views.UpdatesListView.as_view(),name='updates'),
    path('tenders',views.TendersListView.as_view(),name='tenders'),
    path('clubs',views.clubs,name='clubs'),
    path('magazine-team',views.magazine_team,name='magazine-team')
    ]