# Generated by Django 3.2.6 on 2022-11-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='Gallery_categories',
            new_name='Image_category',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
