# Generated by Django 3.2.6 on 2022-11-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0002_auto_20221112_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academiccallink',
            name='acad_link',
        ),
        migrations.AddField(
            model_name='academiccallink',
            name='acad_cal',
            field=models.FileField(blank=True, upload_to='Docs/'),
        ),
        migrations.AddField(
            model_name='academiccallink',
            name='acad_cal_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
