# Generated by Django 4.1 on 2023-03-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0003_auto_20221116_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nirf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, null=True)),
                ('report', models.FileField(blank=True, null=True, upload_to='NIRF/Reports')),
            ],
        ),
    ]
