# Generated by Django 4.1 on 2023-03-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0006_clubs_description_alter_about_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='identifier',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
