# Generated by Django 4.1 on 2023-03-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0008_alter_about_id_alter_aboutustestimonial_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_members',
            name='identifier',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
