# Generated by Django 4.1 on 2023-03-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0009_club_members_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_members',
            name='identifier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
