# Generated by Django 3.1.2 on 2020-10-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0025_auto_20201013_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagegallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='HomePageGallery/'),
        ),
    ]
