# Generated by Django 3.1.2 on 2020-10-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0026_auto_20201020_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campuspagedetails',
            name='image',
        ),
        migrations.AlterField(
            model_name='campuspagegallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='CampusGallery/<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
