# Generated by Django 3.1.2 on 2020-10-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0027_auto_20201020_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Events/%Y/%m/%d<django.db.models.fields.CharField>/'),
        ),
    ]
