# Generated by Django 3.1.2 on 2020-10-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0028_auto_20201020_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campuspagegallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='CampusGallery/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Events/%Y/%m/%d'),
        ),
    ]
