# Generated by Django 3.1.2 on 2021-01-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0029_auto_20201020_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campuspagegallery',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
