# Generated by Django 3.1.2 on 2021-01-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0030_auto_20210106_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campuspagegallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='CampusGallery/<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
