# Generated by Django 3.1.2 on 2021-01-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0031_auto_20210106_1638'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='images',
            new_name='EventsImages',
        ),
        migrations.AddField(
            model_name='campuspagedetails',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='CampusGallery/'),
        ),
        migrations.AddField(
            model_name='campuspagedetails',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='CampusGallery/'),
        ),
        migrations.AddField(
            model_name='campuspagedetails',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='CampusGallery/'),
        ),
        migrations.AddField(
            model_name='campuspagedetails',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='CampusGallery/'),
        ),
        migrations.AddField(
            model_name='campuspagedetails',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='CampusGallery/'),
        ),
        migrations.AddField(
            model_name='campuspagedetails',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='CampusGallery/'),
        ),
        migrations.DeleteModel(
            name='CampusPageGallery',
        ),
    ]
