# Generated by Django 3.2.6 on 2021-09-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0033_auto_20210902_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccallink',
            name='acad_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
