# Generated by Django 3.2.6 on 2021-09-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0034_alter_academiccallink_acad_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicsDSAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=3000)),
                ('description_hindi', models.CharField(max_length=3000)),
                ('description_kannada', models.CharField(max_length=3000)),
                ('academic_calendar_link', models.CharField(max_length=200)),
                ('curriculum_link', models.CharField(max_length=200)),
            ],
        ),
    ]
