# Generated by Django 3.2.6 on 2021-10-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0035_academicsdsai'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Gallery/')),
            ],
            options={
                'verbose_name_plural': 'Gallery',
            },
        ),
    ]
