# Generated by Django 3.2.6 on 2021-10-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0036_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='shape',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
