# Generated by Django 3.2.6 on 2021-10-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0036_announcements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcements',
        ),
    ]
