# Generated by Django 3.2.6 on 2021-10-11 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0037_gallery_shape'),
        ('iiitdsite', '0040_auto_20211010_1058'),
    ]

    operations = [
    ]
