# Generated by Django 3.2.6 on 2021-10-13 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0040_auto_20211010_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='assi_prof_link',
            new_name='Formlink',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='assi_registrar',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='asso_prof_link',
            new_name='instructions',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='audit_officer',
            new_name='job_title',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='office_assistant',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='prof_link',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='project',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='super_accounts',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='super_hrm',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='tech_assistant',
        ),
        migrations.AddField(
            model_name='jobs',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
