# Generated by Django 3.2.6 on 2021-10-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0041_auto_20211013_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_document', models.CharField(max_length=200)),
                ('publishedDate', models.DateField(auto_now_add=True)),
                ('lastDate', models.DateField()),
            ],
        ),
    ]
