# Generated by Django 3.2.6 on 2021-10-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0042_tenders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenders',
            name='publishedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
