# Generated by Django 3.2.6 on 2021-10-13 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0043_alter_tenders_publisheddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenders',
            name='tender_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
