# Generated by Django 3.2.6 on 2021-10-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0045_auto_20211013_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenders',
            name='tender_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
