# Generated by Django 3.2.6 on 2021-10-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0046_tenders_tender_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenders',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
