# Generated by Django 3.2.6 on 2021-10-14 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0041_merge_0037_gallery_shape_0040_auto_20211010_1058'),
        ('iiitdsite', '0047_tenders_time'),
    ]

    operations = [
    ]
