# Generated by Django 3.2.6 on 2021-10-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0048_merge_20211014_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine_Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Magazine/Issues')),
                ('publishedDate', models.DateField()),
            ],
        ),
    ]
