# Generated by Django 3.2.6 on 2021-10-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0048_merge_20211014_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='Clubs/')),
                ('NameofClub', models.CharField(max_length=200)),
                ('Instalink', models.CharField(max_length=200)),
                ('LinkedIn', models.CharField(max_length=200)),
                ('Facebook', models.CharField(max_length=200)),
            ],
        ),
    ]
