# Generated by Django 3.2.6 on 2021-10-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0049_magazine_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine_issues',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
