# Generated by Django 3.2.6 on 2021-10-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0049_clubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='Facebook',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='Instalink',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='LinkedIn',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
