# Generated by Django 3.2.6 on 2021-10-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0050_magazine_issues_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('role', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Magazine/Team/')),
            ],
        ),
        migrations.AlterField(
            model_name='magazine_issues',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Magazine/Issues/'),
        ),
    ]
