# Generated by Django 3.2.6 on 2021-10-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0050_auto_20211015_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='Website',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
