# Generated by Django 3.2.6 on 2021-10-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0051_clubs_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='Mail',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
