# Generated by Django 3.2.6 on 2021-10-17 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0052_clubs_mail'),
        ('iiitdsite', '0052_magazine_team_tag'),
    ]

    operations = [
    ]
