# Generated by Django 3.2.6 on 2021-10-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0054_auto_20211017_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='form',
            field=models.FileField(blank=True, null=True, upload_to='Jobs/'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='instructions',
            field=models.FileField(blank=True, null=True, upload_to='Jobs/'),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Tenders/'),
        ),
    ]
