# Generated by Django 3.2.6 on 2021-10-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0056_alter_jobs_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
