# Generated by Django 3.2.6 on 2021-10-17 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0058_alter_jobs_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchstudents',
            old_name='image_link',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='researchstudents',
            name='name_hindi',
        ),
        migrations.RemoveField(
            model_name='researchstudents',
            name='name_kannada',
        ),
    ]
