# Generated by Django 3.2.6 on 2021-10-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0059_auto_20211017_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phdlinks',
            name='academic_regulations',
        ),
        migrations.RemoveField(
            model_name='phdlinks',
            name='advertisement',
        ),
        migrations.RemoveField(
            model_name='phdlinks',
            name='click_here_to_apply',
        ),
        migrations.RemoveField(
            model_name='phdlinks',
            name='fee_structure',
        ),
        migrations.RemoveField(
            model_name='phdlinks',
            name='instructions_sbi_collect',
        ),
        migrations.RemoveField(
            model_name='phdlinks',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='phdlinks',
            name='sbi_collect',
        ),
        migrations.RemoveField(
            model_name='phdlinks',
            name='scholarships_bank_loans',
        ),
        migrations.AddField(
            model_name='phdlinks',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='phdlinks',
            name='form',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phdlinks',
            name='instructions',
            field=models.FileField(blank=True, null=True, upload_to='PhdAdmission/'),
        ),
        migrations.AddField(
            model_name='phdlinks',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
