# Generated by Django 3.2.6 on 2021-10-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0061_auto_20211019_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial_committee',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
