# Generated by Django 3.2.6 on 2021-10-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0062_financial_committee_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial_committee',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
