# Generated by Django 3.2.6 on 2021-10-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0063_alter_financial_committee_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financial_committee',
            name='order',
        ),
    ]
