# Generated by Django 3.2.6 on 2021-10-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0064_remove_financial_committee_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='name_hindi',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='name_kannada',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='position',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='position_hindi',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='position_kannada',
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
