# Generated by Django 3.2.6 on 2021-10-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0065_auto_20211019_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('designation', models.CharField(max_length=200, null=True)),
                ('department', models.CharField(max_length=200, null=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('interest', models.CharField(max_length=500)),
                ('profile', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Faculty/')),
            ],
        ),
        migrations.DeleteModel(
            name='FacultyPageInfo',
        ),
    ]
