# Generated by Django 3.2.6 on 2021-10-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0066_auto_20211020_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='interest',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='profile',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
