# Generated by Django 3.2.6 on 2021-10-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0067_auto_20211020_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='shape',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
