# Generated by Django 3.2.6 on 2022-09-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0070_auto_20220917_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery_categories',
            name='tag',
        ),
    ]
